name: network_info_plus_apple_tv
description: Flutter plugin for discovering information (e.g. WiFi details) of the network.
version: 0.1.0
homepage: https://plus.fluttercommunity.dev/
repository: https://github.com/epam-cross-platform-lab/network_info_plus_apple_tv/

flutter:
  plugin:
    platforms:
      android:
        package: dev.fluttercommunity.plus.network_info
        pluginClass: NetworkInfoPlusPlugin
      ios:
        pluginClass: FLTNetworkInfoPlusPlugin
      linux:
        default_package: network_info_plus_linux
      macos:
        default_package: network_info_plus_macos
      windows:
        default_package: network_info_plus_windows
      web:
        default_package: network_info_plus_web

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.3.0
  network_info_plus_platform_interface: ^1.0.0
  network_info_plus_linux: ^1.0.0
  network_info_plus_macos: ^1.0.0
  network_info_plus_windows: ^1.0.0
  network_info_plus_web: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.16.4
  mockito: ^5.0.0
  plugin_platform_interface: ^2.0.0
  pedantic: ^1.10.0

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.5"
