name: network_info_plus_platform_interface
description: A common platform interface for the network_info_plus plugin.
version: 1.0.1
homepage: https://github.com/epam-cross-platform-lab/network_info_plus_apple_tv
repository: https://github.com/epam-cross-platform-lab/network_info_plus_apple_tv/

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.3.0
  plugin_platform_interface: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.10.0

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.5"
